### ISSUE TITLE
TEALURLSessionManager Crash

### ISSUE THREAD

**Issue by almog-sears** [Tealium/tealium-ios#64] opened 2018-02-26 14:10 UTC
Hi,

We're experiencing a crash that occurs internally in the SDK and would appreciate your input.
Occurs on iOS 9-11 with latest SDK version (5.3.1).

Thanks,
Almog.
 
![screen shot 2018-02-26 at 15 50 39](https://user-images.githubusercontent.com/23377919/36673846-d96f70ee-1b0c-11e8-8ae3-51dc4bf9ff67.png)

**Comment by craigrouse** [comment] 2018-02-26 14:16
Hello @almog-sears. To help us track this down, it would be useful to know when you started seeing the issue. I'm assuming you are only seeing this issue since updating from 5.3.0 to 5.3.1?

Are there a lot of instances of this exception (I'm assuming this is happening for live app users)? Is it always reproducible or just sporadic?

Thanks,

Craig.

**Comment by almog-sears** [comment] 2018-02-27 10:17
Hi,

Thanks for your quick response.

To answer your questions:

  1.  Yes, it only occurs on 5.3.1.
  2.  We've seen 170 crashes for a similar amount of users in the last 10 days.
  3.  Happens for live users, we couldn't reproduce ourselves. By the number of crashes we can say it's sporadic.

Best,
Almog.

On 26 Feb 2018, at 16:16, Craig Rouse <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @almog-sears<https://github.com/almog-sears>. To help us track this down, it would be useful to know when you started seeing the issue. I'm assuming you are only seeing this issue since updating from 5.3.0 to 5.3.1?

Are there a lot of instances of this exception (I'm assuming this is happening for live app users)? Is it always reproducible or just sporadic?

Thanks,

Craig.

**Comment by craigrouse** [comment] 2018-02-27 10:27
Thanks for the additional info @almog-sears. Sorry to hear this is causing issues for some of your users.

Once you create the Tealium instance, do you ever do any sort of deallocation/destroy the Tealium instance? I suspect this issue may be related to a fix we put in place to avoid memory leaks when the Tealium instance is destroyed. We have, however, tested this with running thousands of iterations of starting up and destroying the instance, but not seen any crashes in the process.

It would be really useful to get hold of the full crash logs for this issue if available, along with a copy of the code you are using to start up (and, if applicable, destroy) the Tealium instance. If you could please send these over to support@tealium.com, referencing this issue, we'll take a look as soon as we can.

We'll do everything we can to get this resolved quickly for you.

**Comment by almog-sears** [comment] 2018-02-27 16:55
Hi,

Attached is the crash log.

Initialization code:
static Tealium* tealiumReporter;

@implementation TealiumInitializer

+ (Tealium*)tealiumInstance {
    if (![self isReporterEnabled])
        return nil;



    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        TEALConfiguration *configuration = [TEALConfiguration configurationWithAccount:[self tealiumSettings].accountName
                                                                               profile:[self tealiumSettings].profileName
                                                                           environment:[TealiumReportingSuite isEqualToString:@"dev"] ? TealiumReportingSuite : [self tealiumSettings].environment];



        tealiumReporter = [Tealium newInstanceForKey:TealiumInstanceKey configuration:configuration];



        [tealiumReporter addRemoteCommandID:RemoteCommandId
                                description:@"Syncs the Session ID"
                                targetQueue:dispatch_get_main_queue()
                              responseBlock:^(TEALRemoteCommandResponse * _Nonnull response) {
                                  NSString *sessionId = response.requestPayload[NativeSessionIdKey];
                                  TealiumSettings.sessionId = sessionId;
                              }];
    });



    return tealiumReporter;
}

We are only calling  [Tealium destroyInstanceForKey:TealiumInstanceKey]; when a server-side switch is activated, as a precaution allowing us to remotely stop reports, but it hasn't been used so far.

**Comment by craigrouse** [comment] 2018-02-27 17:09
Thanks @almog-sears. I've taken a copy of the log file for our internal ticket, and removed it from your comment. We'll be in touch when we have any updates.

**Comment by jonathanswong** [comment] 2018-03-02 22:13
Hi @almog-sears .  We have identified the issue and it will be fixed in the next release.  We will let you know when that release goes out.  Thank you.

**Comment by almog-sears** [comment] 2018-03-05 08:57
Hi Jonathan,

Thanks for the update.

Best,
Almog.

On 3 Mar 2018, at 0:13, Jonathan Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @almog-sears<https://github.com/almog-sears> . We have identified the issue and it will be fixed in the next release. We will let you know when that release goes out. Thank you.

**Comment by jonathanswong** [comment] 2018-03-09 18:42
Hi @almog-sears .  This bug should be fixed in the latest release 5.3.2.  Please let us know if you have any other issues.  Thanks.

**Closed as completed by jonathanswong** 2018-03-09 18:42 UTC
