### ISSUE TITLE
Carthage build throw error: lipo -remove arm64

### ISSUE THREAD

**Issue by a5978445** [Tealium/tealium-ios#99] opened 2019-03-14 02:39 UTC
when i use  Carthage integration tealium-ios  is failure, detail info:

###Cartfile
```

binary "https://tags.tiqcdn.com/dle/tealiummobile/tealium-ios-carthage/tealium-carthage.json"

```

![image](https://user-images.githubusercontent.com/11722240/54327418-06115e00-4645-11e9-9299-d69613e06e4f.png)

### error info
```

warning: Ignoring TealiumIOSLifecycle.framework because it does not support the current architecture

A shell task (/usr/bin/xcrun lipo -remove arm64 -output /Users/litengfang/Library/Developer/Xcode/DerivedData/MFTealiumManager-carwdhdnkqbjnvejpydkrezrkwec/Build/Products/Production\ Debug-iphonesimulator/TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS /Users/litengfang/Library/Developer/Xcode/DerivedData/MFTealiumManager-carwdhdnkqbjnvejpydkrezrkwec/Build/Products/Production\ Debug-iphonesimulator/TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS) failed with exit code 1:
fatal error: /Applications/Xcode10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: -remove's specified would result in an empty fat file

Command PhaseScriptExecution failed with a nonzero exit code

```

Carthage version: 0.32.0
I tried to use different versions of XCode, and it turned out to be，
XCode Version: 9.3 , 10.0, 10.1

**Comment by jonathanswong** [comment] 2019-03-20 18:53
Hi @a5978445 . Thanks for bringing this to our attention. We are currently looking into it. Carthage seems to be downloading a version of the TealiumIOSLifecycle.framework that does not have the simulator slice even though the direct link in the JSON has it. 

In the meantime, if it's blocking you, you possibly could try the following:

- turn off the setting of warnings are errors in Xcode
- manually replace TealiumIOSLifecycle.framework with the TealiumIOSLifecycle.framework in the `master` branch or from the [Releases](https://github.com/Tealium/tealium-ios/releases) page on Github.

**Comment by a5978445** [comment] 2019-04-08 06:46
Ok, please inform me if there is any latest progress

**Comment by christinasund** [comment] 2019-04-12 16:16
Hi @a5978445, thanks for bringing this up to us. We have investigated on our end and filed a bug with Carthage because the architectures from the main archive folder were not ported over correctly. If you see the thread [here](https://github.com/Carthage/Carthage/issues/2764) you will understand that the frameworks in the DevicesOnly folder were overwriting the frameworks in the root folder. 

I don't know if Carthage plans on resolving this on their end, but eventually we will update the DevicesOnly .framework file names to be different than the root. In the mean time, as a workaround, you can remove the frameworks generated by Carthage (in the Carthage/Build/iOS) and manually drag the frameworks from the main archive into the Carthage/Build/iOS folder. 

You can download the archive for the latest version [here](https://github.com/Tealium/tealium-ios/releases).

Let us know if that works for you. Thanks!

**Comment by a5978445** [comment] 2019-04-15 07:23
ok, thank you very much , i will try to use CocoaPod integration it.

**Comment by FranzBusch** [comment] 2019-10-24 03:54
We just encountered the same problem as well with Carthage and the duplicate names of the DevicesOnly folder. The linked bug in the Carthage repo seems to be closed but the issue is still happening for us with the latest Carthage version. Would it be possible to rename the DeviceOnly frameworks or maybe ship them separately. Like attaching them to the release on GitHub?

**Comment by christinasund** [comment] 2019-10-25 04:36
@FranzBusch We released a new version today (5.6.1) that does not include the DevicesOnly framework. Please be aware that this version also includes the high impact changes from version 5.6.0. In this version, we removed the UIWebView. You can read more about his release [here](https://github.com/Tealium/tealium-ios/releases/tag/5.6.0). The main thing to be aware of here is if you are using TagManagement (TiQ) and you have any users on iOS versions < 11.0, the cookies may be reset due to the lack of cookie storage APIs for WKWebView until iOS 11.0. Please let us know if you have any questions or concerns before upgrading. If you have any doubts, you can remove the frameworks generated by Carthage and manually drag the frameworks from the main archive into the Carthage/Build/iOS folder from an earlier version for the time being.

**Comment by FranzBusch** [comment] 2019-10-29 09:26
@christinasund Awesome, thanks for the quick help! We will try it out, this should hopefully resolve the problem we saw during integration with Carthage.

**Comment by christinasund** [comment] 2020-05-28 20:48
Closing due to inactivity, let us know if the problem persists

**Closed as completed by christinasund** 2020-05-28 20:48 UTC
