### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarOrientation]

### ISSUE THREAD

**Issue by flexaddicted** [Tealium/tealium-ios#56] opened 2017-09-08 09:03 UTC
With iOS 11.0, Xcode 9 beta 6, Tealium framework gives the following error:

`Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarOrientation]`

This is the backtrace:

```
4   TealiumIOS                          0x000000010ed5ec33 +[TEALDeviceDataSources currentOrientation] + 59
5   TealiumIOS                          0x000000010ed5dd79 +[TEALDeviceDataSources mainThreadDataSources] + 318
6   TealiumIOS                          0x000000010ed415d0 -[TEALDataSources mainThreadDataSources] + 86
7   TealiumIOS                          0x000000010ed49069 -[Tealium captureTimeDataSourcesForType:title:] + 210
8   TealiumIOS                          0x000000010ed48675 -[Tealium trackType:title:dataSources:completion:] + 228
9   TealiumIOS                          0x000000010ed48531 -[Tealium trackEventWithTitle:dataSources:] + 55
10  TealiumIOSLifecycle                 0x000000010ed2ae84 -[Tealium(Lifecycle) trackLifecycleEventForType:date:persistentData:dataSources:] + 283
11  TealiumIOSLifecycle                 0x000000010ed2ad09 -[Tealium(Lifecycle) executeLifecycleCommandForType:overrideDate:dataSources:autoTracked:] + 412
12  TealiumIOSLifecycle                 0x000000010ed2b0f1 -[Tealium(Lifecycle) enableLifecycleAutotracking] + 62
13  TealiumIOS                          0x000000010ed4bc50 -[Tealium updateModules] + 134
14  TealiumIOS                          0x000000010ed4b683 -[Tealium refresh] + 27
15  TealiumIOS                          0x000000010ed4b6e2 -[Tealium enable] + 76
16  TealiumIOS                          0x000000010ed4b42e -[Tealium finalizeWithConfiguration:completion:] + 1172
17  TealiumIOS                          0x000000010ed4ac8f __57+[Tealium instanceWithConfiguration:delegate:completion:]_block_invoke + 46
18  libdispatch.dylib                   0x00000001150133f7 _dispatch_call_block_and_release + 12
19  libdispatch.dylib                   0x000000011501443c _dispatch_client_callout + 8
20  libdispatch.dylib                   0x000000011501c95b _dispatch_queue_serial_drain + 1162
21  libdispatch.dylib                   0x000000011501d2df _dispatch_queue_invoke + 336
22  libdispatch.dylib                   0x000000011501907d _dispatch_queue_override_invoke + 733
23  libdispatch.dylib                   0x00000001150201f9 _dispatch_root_queue_drain + 772
24  libdispatch.dylib                   0x000000011501fe97 _dispatch_worker_thread3 + 132
25  libsystem_pthread.dylib             0x00000001154d25a2 _pthread_wqthread + 1299
26  libsystem_pthread.dylib             0x00000001154d207d start_wqthread + 13
```

**Comment by interstateone** [comment] 2017-09-15 15:18
This looks like a duplicate of #45

**Comment by jonathanswong** [comment] 2017-12-13 20:27
Hi @interstateone, 

Yes it is a duplicate.  We found the issue and it is fixed in the next release.  Thank you.

**Comment by interstateone** [comment] 2017-12-14 02:04
@jonwong-tealium that's good news! do you have a timeline for this next release?

**Comment by jonathanswong** [comment] 2017-12-14 17:03
@interstateone We do not have a definitive date yet, but most likely early next year.  Thanks.

**Comment by jonathanswong** [comment] 2018-01-08 17:38
Release 5.3.1 is available.  Please let us know if this problem still persists and file a new issue.  Thank you.

**Closed as completed by jonathanswong** 2018-01-08 17:38 UTC
