### ISSUE TITLE
Not all queued data are sent

### ISSUE THREAD

**Issue by wendych864** [Tealium/tealium-ios#47] opened 2017-07-06 14:02 UTC
I use Tealium 5.3.0 and newest Version "Charles" to test whether and when http/https-Requests are sent. 

1. I made mobile data on and wifi not connected on my iPhone. No Special implementation of tealium:shouldQueueDispatch: to track views/Event (return no in this method).
    In this Situation, I clicked in my app to trigger e.g. 7 tracking of views or events. 
    In Charles I saw no tracking request was sent. I guess that the 7 tracking data were queued. 
    Now I made wifi on. I clicked in my app to trigger other  tracking of views/events.
    In Charles I saw the tracking of these views/event were sent and 1 tracking of the 7 queued data before were sent. The other 6 tracking data were not sent any more. 
    
2. I made mobile data off and wifi not connected on my iPhone.  No Special implementation of tealium:shouldQueueDispatch: to track views/Event (return no in this method).
    In this Situation, I clicked in my app to trigger e.g. 7 tracking of views or events. . 
    In Charles I saw no request of these 7 tracking requests was sent. I guess that the 7 tracking data  were queued. 
    Now I made wifi on. I clicked in my app to trigger  other tracking of views/events.
    In Charles I saw the tracking of these views/event were sent and some tracking (not all) of the 7 queued data before were sent. 

My Question:
When mobile data is turned on and wifi is not connected, there is a Internet connection in this situation. 
but why no tracking data are sent in this case? Are these data queued?

 if wifi is turned on, the newly triggered tracking data are sent, but not all the queued data before wifi is turned on are then sent? Why?

**Comment by craigrouse** [comment] 2017-07-06 14:46
@wendych864 this sounds like there is a specific issue with your implementation, since what you have described here is not how queuing was designed. As long as there is a viable internet connection, events should (in most cases) be sent immediately. If there is no connection, events should be queued and sent as soon as a viable connection is active again. I recommend raising a support ticket on support@tealium.com so that one of our support engineers can further assist you and check the config on your Tealium account. Please be sure to include details of the affected account/profile on the support ticket, and a sample app/code if possible.

**Comment by wendych864** [comment] 2017-07-06 15:04
I think that there is no problem with my configuration.

My configuration is as following:
+ (void) startTracking {
#ifdef AD_HOC_DIST
    TEALConfiguration *configuration = [TEALConfiguration configurationWithAccount:TEALIUM_ACCOUNT
                                                                           profile:TEALIUM_PROFILE
                                                                       environment:TEALIUM_ENVIRONMENT_DEV];
#else
#ifdef DEBUG
    TEALConfiguration  *configuration = [TEALConfiguration configurationWithAccount:TEALIUM_ACCOUNT
                                                                           profile:TEALIUM_PROFILE
                                                                       environment:TEALIUM_ENVIRONMENT_DEV];
#else
    TEALConfiguration *configuration = [TEALConfiguration configurationWithAccount:TEALIUM_ACCOUNT
                                                                           profile:TEALIUM_PROFILE
                                                                        environment:TEALIUM_ENVIRONMENT_PROD];
#endif
#endif
    configuration.collectPollingFrequency = TEALVisitorProfilePollingFrequencyOnRequest;
    Tealium *tealiumInstance1 = [Tealium newInstanceForKey:TEALIUM_INSTANCE_ID configuration:configuration];
    
    [tealiumInstance1 setDelegate:[TealiumHelper sharedInstance]];
}

- (BOOL) tealium:(Tealium *)tealium shouldQueueDispatch:(TEALDispatch *)dispatch {
    // Add optional queuing / saving logic here - returning YES will save
    // a dispatch so some condition must eventually return NO.
    return NO;
}

If wifi is on I can see in in Http/https-monitoring tool "Charles" Charles that tracking data are sent.

If wifi is not turned on and mobile data is on, in Http/https-monitoring tool "Charles" no tracking data is sent. After wifi is turned on, the tracking data that were not sent before are not sent afterwards any more.
I think it may be a problem in Tealium-Framework.

**Comment by wendych864** [comment] 2017-07-06 15:26
I use the sample "UIKitCatalog+Tealium-ObjC" (https://github.com/Tealium/tealium-ios/tree/master/Samples/iOS_UIKitCatalog%2BTealium_ObjC) and Charles to test whether and when the tracking data are sent.

If wifi is not turned on and mobile data is turned on on my iPhone, no tracking data is sent (I saw no tracking data sent in Charles).

After wifi is then turned on, newly triggered tracking data are sent and the tracking data before the wifi was turned on are not sent any more.  The same result as I stated before with my app.

**Comment by jalakoo** [comment] 2017-07-06 15:42
Hi @wendych864, Craig is referring to the Tealium account configuration on our system (i.e. is Collect and/or Tag Management enabled, what tags if any are enabled) and the mobile remote publish settings which can override some local settings.  Your dev side configuration does look correct.

**Comment by wendych864** [comment] 2017-07-06 15:50
@jalakoo
Thank you for your reply.  What need I do refering to configuration on your System and the mobile remote publish Setting? Do you mean that you will check on your System?

**Comment by craigrouse** [comment] 2017-07-07 09:03
@wendych864 the publish settings are stored in your Tealium iQ profile, and options include "send events only over wifi". We will need to check these settings, as well as the way the tags are configured in your profile to confirm that the issues you are seeing are not being caused by your profile settings.

**Comment by craigrouse** [comment] 2017-07-20 13:57
@wendych864 I will close this issue for now, since we haven't had any further info from you, but please feel free to comment and reopen if necessary.

**Closed as completed by craigrouse** 2017-07-20 13:57 UTC

**Comment by wendych864** [comment] 2017-07-25 08:31
@craigrouse 
the options you mentioned may have no effect on the problem I reported. 
I used your sample "UIKitCatalog+Tealium-ObjC" in https://github.com/Tealium/tealium-ios/tree/master/Samples/iOS_UIKitCatalog%2BTealium_ObjC and "Charles" to test whether and when the tracking data are sent out from my iPhone. The problem I reported are that the tracking data are not sent out from my iPhone if mobile data (3G or LTE) is turned on and wifi is off on my iPhone and If wifi is then turned on on iPhone, not all of the tracking data that were NOT sent before are sent out from my iPhone afterwards. With Tealium all the tracking data should be sent out afterwards. All the tracking data should be sent if mobile data on my iPhone is turned on. 
The problem I reported is not that the tracking data are not written on server, but the data are not sent out from my iPhone.

Please try to test the first problem of two problems I reported with your sample  "UIKitCatalog+Tealium-ObjC" on GitHub and a HTTP/HTTPs minitoring tool for example "Charles".
If you download "Charles" program on you computer and configure it so that Charles can track 
when and what data are sent out and received on your iPhone through your computer.
Then you donwload your sample "UIKitCatalog+Tealium-ObjC" in https://github.com/Tealium/tealium-ios/tree/master/Samples/iOS_UIKitCatalog%2BTealium_ObjC onto your computer, run the program on your iPhone, start "Charles" on your computer to monitor what are sent out and received on your iPhone and click in "UIKitCatalog+Tealium-ObjC" app to start tracking,  you will see that tracking data are not sent out from your iPhone if wifi on your iPhone was firstly NOT turned on and 3G or LTE is turned on. And then turned wifi on and connect you iPhone with wifi and click tracking in ""UIKitCatalog+Tealium-ObjC" to trigger tracking,  you will see that NOT all of the tracking data that were NOT sent are sent out from your iPhone afterwards. 

In this case where could you look up the Tealium iQ profile and options include "send events only over wifi" ans so on? I think, the problem has nothing to do with profile and options.

**Comment by craigrouse** [comment] 2017-07-25 19:41
@wendych864 I will attempt to repeat the test you have outlined, but as previously requested, please also send a support case to support@tealium.com with full details of your account and profile. There are many reasons why a problem in your Tealium iQ config could interfere with data being sent successfully from the device. It sounds like you possibly don't have access to your Tealium iQ profile, so you may need to speak to your internal Tealium admin person to get them to raise the case on your behalf. I will test tomorrow and report back.
