### ISSUE TITLE
Tealium Crash iOS 11 enableRemoteCommands

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [Tealium/tealium-ios#62] opened 2018-01-19 11:35 UTC
HI there,
We are using the Tealium Library as a pod with version 5.3. Now in production we have a lot of crashes in the function enableRemoteCommands. I attached a screenshot of the callstack. Has anybody the same problems. We do not use this method in our code. It seems that the release of that object crashed. We are using version 5.3.0. To install the tealium library we use the command pod 'TealiumIOS', '~> 5.3'. We still get the version 5.3.0, but it seems there is a newer version available!

![tealium](https://user-images.githubusercontent.com/35596604/35149120-3effbaba-fd15-11e7-8693-de862663a402.jpeg)

**Comment by craigrouse** [comment] 2018-01-19 11:59
@andreas-sommer-engenious I'm hoping that 5.3.1 will fix this for you. Is the issue reproducible? At what point is the crash happening; is it immediately after initialising the library?

You may need to run pod update to get the latest CocoaPods packages, which should pull in 5.3.1. Otherwise, try removing the explicit version and just leave `pod TealiumIOS` and then do another `pod install`

**Comment by andreas-sommer-engenious** [comment] 2018-01-19 12:11
No the issue is not reproducible. We still have a lot of crashlogs from apple. We only get the call stack that I posted above. 
I removed the TealiumIOS from the pod file, then run "pod install" and then add the command again and still get the 5.3.0 version. Any idea? Don't know whats wrong.

**Comment by craigrouse** [comment] 2018-01-19 12:16
@andreas-sommer-engenious what if you try to use 'TealiumIOS', '5.3.1' in your Podfile? It sounds like your local CocoaPods install is using a cached version of the pod, and possibly needs to be forced into updating.

With regard to the specific crash, it would be great if you can share the full crash logs with us, along with any code (such as helper classes) you are using to initialise your Tealium tracking, and perform tracking calls. If you don't want to share this here, please email support@tealium.com and reference this issue.

**Comment by andreas-sommer-engenious** [comment] 2018-01-19 12:25
Yes thanks. pod update helped to solve the version problem.
Here is the code in a tracking class:
- (id)init {
	
	self = [super init];
	ABCEnvironment *environment = [[ABCEnvironmentManager manager] currentEnvironment];
	if (environment != nil) {
		// Set your account, profile, and environment
		TEALConfiguration *configuration = [TEALConfiguration configurationWithAccount:environment.trackingAccount profile:environment.trackingProfile environment:environment.trackingTarget];
		[configuration setOverrideTagManagementURL:environment.trackingURL];
		
#if defined(CONFIGURATION_Debug)
		//[configuration setLogLevel: TEALLogLevelDev];
#endif
		
		if ([TEALConfiguration isValidConfiguration:configuration]) {
			
			// Initialize with a unique key for this instance
			Tealium *tealiumInstance = [Tealium newInstanceForKey:kTrackingWriterAdobeTealiumKey1 configuration:configuration];
			tealiumInstance.delegate = self;
			
			[tealiumInstance addRemoteCommandID:kTealiumSyncSessionId
										 description:@"Syncs the Session ID"
										 targetQueue:dispatch_get_main_queue()
			 // response is generated from the mappings set up in Tealium iQ
									   responseBlock:^(TEALRemoteCommandResponse * _Nonnull response) {
										   // grab the Session ID from the response object
										   [[dbnAppSettingsManager sharedManager] setValue:response.requestPayload[@"sessionId"] forKey:kTealiumSyncSessionId];
									   }];
		}
	}

	[[dbnAppSettingsManager sharedManager] addSettingsObserver:self];
	BOOL withTracking = [[[dbnAppSettingsManager sharedManager] getUserSettingsValue:TrackingOn] boolValue];
	if( withTracking ) {
		
		[ADBMobile setPrivacyStatus:ADBMobilePrivacyStatusOptIn];
	}
	else {
		
		[ADBMobile setPrivacyStatus:ADBMobilePrivacyStatusOptOut];
	}
	return self;
}

- (BOOL) tealium:(Tealium *)tealium shouldDropDispatch:(TEALDispatch *)dispatch {
       // Depending if the user has disabled the tracking option
	return NO;
}

- (void) tealium:(Tealium *)tealium didSendDispatch:(TEALDispatch *)dispatch {
	//NSLog(@"Tealium: %@", dispatch.payload);
}

And then we track data like:

		[[Tealium instanceForKey:kTrackingWriterAdobeTealiumKey1] trackType:TEALDispatchTypeView title:state.pagename dataSources:state.contextVars completion:^(TEALDispatchStatus status, TEALDispatch * _Nonnull dispatch, NSError * _Nullable error) {
			//NSLog(@"Tealium: %@", state.contextVars);
		}];

**Comment by craigrouse** [comment] 2018-01-19 13:32
@andreas-sommer-engenious thanks for the crash logs. We need to do more testing on this issue. It could possibly be to do with the fact that you are overriding the Tag Management URL.

For now, you can try changing your init code to disable the Remote Commands feature (since you're not using it):

On your config object, call:

`[configuration setRemoteCommandsEnabled:NO];`

We will look into this further and hopefully be able to reproduce it with the code you've provided. I don't think the 5.3.1 changes will directly help with this crash, but I would still advise upgrading, as there were many other issues fixed with this release.

I'll leave this issue open until we have a fix.

**Comment by andreas-sommer-engenious** [comment] 2018-01-19 13:42
Ok, thanks a lot. I will wait for your response.

**Comment by craigrouse** [comment] 2018-01-19 13:46
Thanks @andreas-sommer-engenious. Let me know if disabling remote commands fixes the issue for you.

**Comment by andreas-sommer-engenious** [comment] 2018-01-22 07:37
What exactly are the remote commands doing? Thanks.

**Comment by craigrouse** [comment] 2018-01-22 11:26
@andreas-sommer-engenious RemoteCommands allow certain pre-determined blocks of native code to be executed from a Tealium iQ callback. You can read more here: https://community.tealiumiq.com/t5/Tealium-for-Swift/General-Mobile-Concepts/ta-p/20532#toc-hId-1330093625

I hope this helps.

**Comment by mrbtuts** [comment] 2018-03-08 12:28
I had similar issue on using in Podfile. Most probably because it installed a cache version of TealiumIOS so upon making the update got it resolve. [Showbox](https://showbox.onl/) [Mobdro](https://mobdro.one/) [Tutuapp](https://dltutuapp.com/)

**Comment by jonathanswong** [comment] 2018-03-14 22:29
Hi @andreas-sommer-engenious .  Are you still having crashes with

- 5.3.1 library installed
- remote commands disabled `[configuration setRemoteCommandsEnabled:NO];`

Thanks.

**Comment by andreas-sommer-engenious** [comment] 2018-03-26 11:21
Yes,
We still have crashes when we call addRemoteCommandID:
[tealiumInstance addRemoteCommandID:kDBNavigatorTealiumSyncSessionId
										 description:@"Syncs the Session ID"
										 targetQueue:dispatch_get_main_queue()
			 // response is generated from the mappings set up in Tealium iQ
									   responseBlock:^(TEALRemoteCommandResponse * _Nonnull response) {
										   // grab the Session ID from the response object
										   [[dbnAppSettingsManager sharedManager] setValue:response.requestPayload[@"sessionId"] forKey:kDBNavigatorTealiumSyncSessionId];
									   }];

We need to store the session ID. Do you have any ideas. 
Regards
Andreas





____________________________________________________________ 
engenious GmbH
 
Dipl.-Ing.
Andreas Sommer
Geschäftsführer
 
Julia-Lanz-Straße 1
68782 Brühl
Germany
 
Phone:   +49 (6202) 9298303
Mobile:  +49 (177)   6735979
 
Email:    andreas.sommer@engenious.de
Web:      www.engenious.de
 
Amtsgericht Mannheim | Handelsregisternummer HRB 723200
St.-Nr.: 43040/15259 | Ust.-ID: DE302103499
Geschäftsführer | CEO: Andreas Sommer, Rüdiger F. Lorbeer

**Comment by andreas-sommer-engenious** [comment] 2018-03-26 11:23
This is the call stack of the crash:

Regards 
Andreas





____________________________________________________________ 
engenious GmbH
 
Dipl.-Ing.
Andreas Sommer
Geschäftsführer
 
Julia-Lanz-Straße 1
68782 Brühl
Germany
 
Phone:   +49 (6202) 9298303
Mobile:  +49 (177)   6735979
 
Email:    andreas.sommer@engenious.de
Web:      www.engenious.de
 
Amtsgericht Mannheim | Handelsregisternummer HRB 723200
St.-Nr.: 43040/15259 | Ust.-ID: DE302103499
Geschäftsführer | CEO: Andreas Sommer, Rüdiger F. Lorbeer

**Comment by jonathanswong** [comment] 2018-03-26 15:14
Hi @andreas-sommer-engenious .  Can you please send an email to support@tealium.com so we can better diagnose your problem.  Thank you.

**Comment by jonathanswong** [comment] 2018-10-18 19:20
Hi @andreas-sommer-engenious . Are you still seeing this issue? Thanks.

**Comment by jonathanswong** [comment] 2018-10-22 19:48
Hi @andreas-sommer-engenious . Please let us know if this issue is still happening and is not resolved. We'll close it for now. Thank you.

**Closed as completed by jonathanswong** 2018-10-22 19:48 UTC
